services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    restart: always

networks:
  app-network:
    driver: bridge